app/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
from .views import export_to_excel

urlpatterns = [
    #path('', views.home, name="home"),
    path('', views.index, name='index'),
    path('service/', views.service, name="service"),
    path('service_low/', views.service_low, name="service_low"),
    path('service_high/', views.service_high, name="service_high"),
    path('warning_spider/', views.warning_spider, name="warning_spider"),  
    path('warning_dspm/', views.warning_dspm, name="warning_dspm"),
    path('warning_scada/', views.warning_scada, name="warning_scada"),
    path('warning_mtmn/', views.warning_mtmn, name="warning_mtmn"),
    path('warning_data/', views.warning_data, name="warning_data"),    
    path('base/', views.base, name="base"),
    path('chart_system/', views.chart_system, name="chart_system"),    
    path('chart_fee/', views.chart_fee, name="chart_fee"),
    path('chart_fee_system/', views.chart_fee_system, name="chart_fee_system"),    
    # Other URL patterns
    path('export/', export_to_excel, name='export_to_excel'),
    # Other URL patterns
    path('export_query_to_csv/', views.export_query_to_csv, name='export_query_to_csv'),
    #tạo table
    path('addnew',views.addnew, name='addnew'),  
    path('edit/<int:serial>', views.edit, name='edit'),  
    path('update/<int:serial>', views.update, name='update'),  
    path('delete/<int:serial>', views.destroy, name='destroy'),  
]

qltb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    department_id = models.IntegerField(primary_key=True)
    department = models.CharField(max_length=50 ,null=False, default='Công ty điện lực Quảng Trị')
    def __str__(self):
        return self.department
    
class Network(models.Model):
    network_id = models.CharField(primary_key=True, max_length=50)
    network = models.CharField(max_length=50 ,null=False, default='1')
    def __str__(self):
        return self.network

class System(models.Model):
    id = models.AutoField(primary_key=True)
    system = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return str(self.system)

class Status(models.Model):
    id = models.AutoField(primary_key=True)
    status = models.CharField(max_length=255, null=True, blank=True)
    def __str__(self):
        return str(self.status)

class Phone(models.Model):
    id = models.IntegerField (null=True,blank=True)
    phone = models.IntegerField(null=True,blank=True)
    serial = models.BigIntegerField(primary_key=True, blank=True)
    pack = models.CharField(max_length=255, null=True,blank=True)
    money = models.IntegerField(null=True,blank=True)
    date_connect = models.DateField(null=True,blank=True)
    department_id = models.ForeignKey(Department, on_delete=models.CASCADE,blank=True,null=True)
    date_join = models.DateField(null=True,blank=True)
    status_id = models.ForeignKey(Status, on_delete=models.CASCADE,blank=True,null=True)
    system_id = models.ForeignKey(System, on_delete=models.CASCADE,blank=True,null=True)
    network_id= models.ForeignKey(Network, on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return f"{str(self.serial)}, {self.phone}, {self.department_id}, {self.status_id}, {self.system_id}, {self.network_id}"

class PhoneItem(models.Model):
    id = models.AutoField(primary_key=True)
    serial = models.ForeignKey(Phone,on_delete=models.CASCADE,blank=True,null=True)
    date_use = models.DateField(null=True,blank=True)
    data = models.IntegerField(null=True,blank=True)
    def __str__(self):
        return str(self.id)

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Bootstrap CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">        
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"/>
    <link rel = "stylesheet" type = "text/css" href = "https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css"/>
    <link rel = "stylesheet" type = "text/css" href = "https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css"/>
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href={% static "app/css/style.css" %}/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <link type="text/javascript" href={% static "app/js/Chart.js" %}/>
    <link type="text/javascript" href={% static "app/js/Chart.min.js" %}/>
    <!-- Font Awesome JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    <script type="text/javascript">
        var user='{{request.user}}'
        function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');
      </script>
</head>

<body>

    <div class="wrapper" >
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>MENU</h3>
                <strong>O</strong>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="{% url 'index' %}" >
                        <i class="fas fa-home"></i>
                        Danh sách thuê bao
                    </a>
                </li>
                <li>
                    <a href="{% url 'warning_spider' %}" >
                        <i class="fas fa-exclamation-triangle"></i>
                        Cảnh báo cước
                    </a>
                </li>
                <li>
                    <a href="{% url 'service' %}">
                        <i class="fas fa-briefcase"></i>
                        Quản lý DATA
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        Báo cáo
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'chart_system' %}">Quản lý thuê bao</a>
                        </li>
                        <li>
                            <a href="{% url 'chart_fee' %}">Chi phí trong kỳ</a>
                        </li>
                        <li>
                            <a href="{% url 'chart_fee_system' %}?chat_fee_system=1">Chi phí theo đơn vị</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-image"></i>
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-question"></i>
                        FAQ
                    </a>
                </li>                
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:10px">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Hide</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active" style="width:30px">
                                <a href="{% url 'index' %}" >
                                    <i class="fas fa-home"></i></a>
                            </li>
                            <li class="nav-item active" style="width:30px">
                                <a href="{% url 'warning_spider' %}" >
                                    <i class="fas fa-exclamation-triangle"></i></a>
                            </li>
                            <li class="nav-item" style="width:30px">
                                <a href="{% url 'service' %}" >
                                    <i class="fas fa-briefcase"></i>
                                </a>
                            </li>
                            <li class="nav-item" style="width:30px">
                                <a href="{% url 'chart_system' %}" >
                                    <i class="fas fa-copy"></i>
                                </a>
                            </li>
                            <li class="nav-item" style="width:30px">
                                <a href="{% url 'index' %}" >
                                    <i class="fas fa-image"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            
            <div class="container">
                <div class="row">
                   {% block content %}{% endblock %}
                </div>
               </div>            
        </div>  
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src = "https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
    <link type="text/javascript" href={% static "app/js/Chart.js" %}/>
    <link type="text/javascript" href={% static "app/js/Chart.min.js" %}/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#bootstrapdatatable').DataTable({     
          "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
            "iDisplayLength": 10
           } 
        );
    } );
    </script>
    <script>
        $(document).ready(function() {
            $('#example').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                "iDisplayLength": 10
            } );
        } );
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
    


    
</body>

</html>

app/templates/app/chart_fee.html
{% extends "app/base.html" %}
{%load static%}
  
{% block content %}
<div id="content-wrapper" style="padding-top: 5px">
    <div class="row">
        <div class="col-lg-8 mb-4 order-0" style="width:450px">
          <div class="card">
            <div class="d-flex align-items-end row">
              <div class="col-sm-7">
                <div class="card-body">
                  <h5 class="card-title text-primary">Thống kê:</h5>
                  Đến ngày <script>
                    date = new Date().toLocaleDateString();
                    document.write(date);
                  </script>
                  <p class="card-title mb-2">Tổng cước hàng tháng của toàn Công ty là: <span class="fw-medium"><strong>{{totalfee}} đồng</strong></span></p>
                  <a href="{% url 'index' %}" class="btn btn-sm btn-outline-primary">Danh sách thuê bao</a>
                </div>
              </div>
              <div class="col-sm-5 text-center text-sm-left">
                <div class="card-body pb-0 px-0 px-md-4">
                  <img src="{% static  'app/image/money.png' %}" height="140"  >
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 order-1" style="width:650px">
          <div class="row">
            <div class="col-lg-6 col-md-12 col-6 mb-4" style="width:230px">
                <div class="card">
                  <div class="card-body">
                    <div class="card-title d-flex align-items-start justify-content-between">
                      <div class="avatar flex-shrink-0">
                        <img src="{% static 'app/image/Mobifone.png' %}" alt="chart success" class="rounded" width="30" height="30">
                      </div>
                    </div>
                    <span class="fw-medium d-block mb-1">Cước hàng tháng dịch vụ Mobifone:</span>
                    <p class="card-title mb-2"><span class="fw-medium"><strong>{{totalmobifone}} đồng</strong></span></p>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 col-md-12 col-6 mb-4" style="width:200px">
              <div class="card">
                <div class="card-body">
                  <div class="card-title d-flex align-items-start justify-content-between">
                    <div class="avatar flex-shrink-0">
                      <img src="{% static 'app/image/Viettel.png' %}" alt="chart success" class="rounded" width="30" height="30">
                    </div>
                  </div>
                  <span class="fw-medium d-block mb-1">Cước hàng tháng dịch vụ Viettel:</span>
                  <p class="card-title mb-2"><span class="fw-medium"><strong>{{totalviettel}} đồng</strong></span></p>
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-md-12 col-6 mb-4" style="width:200px">
                <div class="card">
                  <div class="card-body">
                    <div class="card-title d-flex align-items-start justify-content-between">
                      <div class="avatar flex-shrink-0">
                        <img src="{% static 'app/image/Vinaphone.png' %}" alt="chart success" class="rounded" width="30" height="30">
                      </div>
                    </div>
                    <span class="fw-medium d-block mb-1">Cước hàng tháng dịch vụ Vinaphone:</span>
                    <p class="card-title mb-2"><span class="fw-medium"><strong>{{totalvinaphone}} đồng</strong></span></p>
                  </div>
                </div>
            </div>
          </div>
        </div>
    </div>
    <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Overview</li>
        </ol>

        <!-- Icon Cards-->
        <div class="row">
            <div class="col-sm-6">    
                <canvas id="myChart" width="300" height="200"></canvas>
                    <div>
        
        <script type="text/javascript">
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for course in depart_list %} '{{ course }}', {% endfor %}],
                    datasets: [{
                        label:'Chi phí dịch vụ nhà mạng theo đơn vị (đồng)',
                        data: [{% for number in numderpart_list %} '{{ number }}', {% endfor %}] ,
                        backgroundColor:[
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 135, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(151, 102, 132, 1)',
                        'rgba(153, 99, 132, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 135, 1)',
                        'rgba(25, 206, 86, 1)',
                        'rgba(211, 192, 192, 1)',
                        'rgba(234, 102, 132, 1)',
                        'rgba(153, 99, 132, 1)',
                        'rgba(255, 159, 64, 1)',
                        'gree',
                        'yellow',
                        ],
        
                        borderColor: [
                        'rgba(54, 162, 135, 1)',
                        'rgba(25, 206, 86, 1)',
                        'rgba(211, 192, 192, 1)',
                        'rgba(234, 102, 132, 1)',
                        'rgba(153, 99, 132, 1)',
                        'rgba(255, 159, 64, 1)',
        
                        ],
        
                        borderWidth: 1
                    }]
                },
        
                options: {
                    scales: { 
                        xAxes: [{
                            ticks: {
                                beginAtZero: true,                                
                                maxRotation: 90,
                                minRotation: 90
                            }
                        }]
                    }
                }
            })
        </script>        
                    </div> 
                </div>

            <div class="col-sm-6">    
            <canvas id="myChart1" width="300" height="200"></canvas>
                <div>

<script type="text/javascript">
var ctx = document.getElementById('myChart1').getContext('2d');
var myChart1 = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: [{% for course in course_list %} '{{ course }}', {% endfor %}],
        datasets: [{
            label:'chi phí dịch vụ theo chương trình (đồng)',
            data: [{% for number in number_list %} '{{ number }}', {% endfor %}],
            backgroundColor:[
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 135, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(151, 102, 132, 1)',
            'rgba(153, 99, 132, 1)',
            'rgba(255, 159, 64, 1)',
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 135, 1)',
            'rgba(25, 206, 86, 1)',
            'rgba(211, 192, 192, 1)',
            'rgba(234, 102, 132, 1)',
            'rgba(153, 99, 132, 1)',
            'rgba(255, 159, 64, 1)',
            'gree',
            'yellow',
            ],

            borderColor: [
            'rgba(54, 162, 135, 1)',
            'rgba(25, 206, 86, 1)',
            'rgba(211, 192, 192, 1)',
            'rgba(234, 102, 132, 1)',
            'rgba(153, 99, 132, 1)',
            'rgba(255, 159, 64, 1)',

            ],

            borderWidth: 1
        }]
    },

    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
})
</script>        
                </div>
            </div>            
        </div>
<!-- end of static icon -->           
    </div>
</div>
{% endblock content %}

app/templates/app/home.html
{%extends 'app/base.html'%}
{%load static%}
{%block home_page%}
<div>
  <section>
    <!--Table-->
    <div class="d-flex flex-row">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">đơn vị</a>
            <ul class="dropdown-menu">
              {% for i in departments %}
              <li><a class="dropdown-item" href="{% url 'home' %}?department_id={{i.department}}">{{i.department}}</a></li>
              {% endfor %}
            </ul>
            <button class="btn btn-outline-success" type="submit">Search</button>
    </div>
    <div style ="text-align:right;">
        <li >
            <a href="{% url 'export_to_excel' %}"> <img src="{% static 'app/image/export_excel.png' %}" width="30" height="30" >Excel</a>
            <a href="{% url 'export_query_to_csv' %}"> <img src="{% static 'app/image/csv.png' %}" width="30" height="30" >CSV</a>  
        </li>   
    </div>
    <table class="table table-hover table-fixed">
        <!--Table head-->
        <thead>
            <tr>
                <th>ID</th>
                <th>Phone</th>
                <th>Serial</th>
                <th>Gói cước</th>
                <th>đơn giá</th>
                <th>Ngày hòa mạng</th>
                <th>Đơn vị</th>
            </tr>
        </thead>
        <!--Table head-->

        <!--Table body-->
        <tbody>
            {% for phone in phone_list%}
            <tr>
                <th scope="row">{{phone.id}}</th>
                <td>{{phone.phone}}</td>
                <td>{{phone.serial}}</td>
                <td>{{phone.pack}}</td>
                <td>{{phone.money}}</td>
                <td>{{phone.date_connect}}</td>
                <td>{{phone.department_id}}</td>
            </tr>
            {% endfor %}
            
        </tbody>
        <!--Table body-->
    </table>
    <!--Table-->
</section>
</div>
{%endblock home_page%}

app/templates/app/index.html
{% extends "app/base.html" %}
  
{% block title %}Add New Phone Records{% endblock title %}
  
{% block content %}
<div class="col-md-12">    
    <form method="POST" class="post-form" action="/addnew">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>THÊM MỚI THUÊ BAO</h3>  
        </div>    
     
        <div class="mb-3"> 
            <label>Số điện thoại:</label>  
            {{ form.phone }}   
        </div> 
        <div class="mb-3"> 
            <label>Serial:</label>  
            {{ form.serial }}   
        </div>  
        <div class="mb-3"> 
            <label>Gói cước:</label>  
            {{ form.pack }}   
        </div>
        <div class="mb-3"> 
            <label >Thành tiền:</label>  
            {{ form.money }}   
        </div>
        <div class="mb-3">       
            <label>Ngày hòa mạng:</label>
            {{ form.date_connect }} 
        </div>
        <div class="mb-3"> 
            <label>Đơn vị sử dụng:</label>
            {{ form.department_id }}   
            {% comment %} <select id="id_department" name="department" class="form-control" >
                <option value="{{ phone.department_id }}" selected data-default>{{phone.department_id}}</option>
                {% for depart in departments %}
                    <option value="{{depart.department_id}}" >{{depart.department}}</option>
                {% endfor %}
            </select> {% endcomment %}
        </div>
        <div class="mb-3" >
            <label>Ngày sử dụng:</label>              
            {{ form.date_join }} 
        </div>
        <div class="mb-3">       
            <label>Trạng thái:</label>
            {{ form.status_id }} 
        </div>
        <div class="mb-3">       
            <label>Hệ thống sử dụng:</label>
            {{ form.system_id }} 
        </div>
        <div class="mb-3">       
            <label>Nhà mạng:</label>
            {{ form.network_id }} 
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-primary">Submit</button>    
        </div> 
    </div>  
    </form>  
</div> 
{% endblock content %} 